### ISSUE TITLE
Discontinuity in spline on either side of breakpoint in the envelopes figures

### ISSUE THREAD

**Issue by BenjaminDalziel** [rachaelaber/2023_paper#29]
In heuristic_envelope.R the spline for mu "jumps" as it crosses the breakpoint. I wonder if it is because of how the spline is behaving at the beginning and end of the time series it is being fitted to. In other words, when we fit mu in 2 parts the spline that ends at thanksgiving doesn't match up with the spline that begins the next day.

This may be a separate issue, but the p-values also don't make sense to me. The county with index=1 has a wald p-value of 0.44, but it looks like there are a lot more points outside the envelope post-thanksgiving.

**Comment by BenjaminDalziel** [comment]
I added a line for mu to the plots so you can see the discontinuity. 
The commit is 44e85e7130a83544924d1413f3e87917ff09e41e.

**Comment by rachaelaber** [comment]
Yeah, I think that unless we fit a spline model to the whole time series, there is no guarantee that the splines will meet at Thanksgiving.

Also, I think that the Wald p-values may not be exactly reflective of what we're seeing in raw dispersion values since the hypothesis test is on the log scale (see code in W.R).
